# Generated by Django 5.1.7 on 2025-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
